apiVersion: v1
kind: Service
metadata:
  name: vllm-svc
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vllm-svc
  namespace: default
subsets:
  - addresses:
      - ip: 100.82.135.124
    ports:
      - port: 8000
        protocol: TCP
